### PR TITLE
Initialize bookstore

### PR DESCRIPTION
**Pull request by Ntwali-Josue**
### In this Pull Request, I:

- Initialise React app.
- Add React-Redux (npm install react-redux).
- Structure my application files using a "feature folder" approach and use the duck's pattern for your Redux files. My folder structure looks like this:

```
/src
    |---/components
    |---/redux
        |--- /books
                | books.js
        |--- /categories
                | categories.js
        | cofigureStore.js
    | index.js
```
- The building blocks of my app are set as re-usable components.
- Add React Router and set two <Route>s and <Link>s for the app's navigation:

1. Books - the default 

- Display the list of books
- Should have a form for adding a book (no functionality yet)

2. Categories

- Display "Under construction" text only.

### CODE REVIEW

**Review by dasileker — CHANGES_REQUESTED** [review]
### **Hi @Ntwali-Josue,** 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️
_Check the comments under the review._

- The project looks good but you missed the part that you should put the `Book.js && category.js ` in the redux folder not in the component folder

lmlml


## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
-N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by Ntwali-Josue** [comment]
Oh Thanks a lot @dasileker for pointing this out, I did not realize it. I am going to work on it 💯 .

**Review by barackm — CHANGES_REQUESTED** [review]
Hi @Ntwali-Josue, 👋 

Great work on making the changes requested by a previous reviewer 👏 👏👏
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet. 😉  😉 

 # STATUS: Required Changes ♻️
### _Check the comments under the review._ 👇 

- [ ] It seems that there was confusion on what the previous reviewer requested, so let me try to explain a bit what he meant 😉 
image
Following the screenshot above ☝️ 
the files `books.js` and `categories.js`  should be in the `redux` folder and not `BookItem.js` or `BookList.js`. but why?? this is because in the `redux` folder we don't need to have React components, instead, we only need reducers which are: `books.js and categories.js` for now. and these files do can even be empty for now. The files `BookItem.js` or `BookList.js` are actually React components which means, they have to be located in the `components` folder instead of the `redux` folder 😉 



## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Review by GzimAsani — APPROVED** [review]
# STATUS: APPROVED :100:         

## Thank you for implementing all the project requirements, you've done a great job :trophy:  . There is nothing else to say other than... it's time to merge it :champagne:  :tada: Congratulations

Cheers and Happy coding! :clap:  :computer:  :wine_glass: 
Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


 **_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**
 
 _As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

**Comment by Ntwali-Josue** [comment]
@barackm now I understand well, I was a bit confused on it. Thanks a lot for these descriptive explanations.

**Comment by Ntwali-Josue** [comment]
@GzimAsani Thanks a lot for approving my project 😀

**Pull request merged**
